%%%%%%%%%%% Definition of the PV cell structure (2nd component) %%%%%%%%%%%

% Defined as an array of structures, each structure representing a layer
% provided from front to back
% The temperature must be the same in each layer
% The surface recombination velocity "Sr" field must only be provided for
% the two extreme layers of the optoelectronic component. Only the layers
% in between these layers (including them) are included in the electrical
% simulation.

function d = structure_PV()

    d = [struct('T',300, ...                    % temperature (K)
                'fmat',@Properties_InGaP, ...   % function used for material properties
                'x',0.41, ...                   % alloy fraction - here of In (-)
                'Eu',0, ...                     
                'tj',20e-9, ...                 % layer thickness (m)
                'Nzr',51, ...                   % size of the spatial grid in the rad. solver
                'Nze',501, ...                  % size of the spatial grid in the elec. solver
                'Ndop',1e25, ...                % doping level, unsigned (m^-3)
                'DopSign',-1, ...               % doping sign (-1: donor, +1: acceptor)
                'Sr',1e2);                      % surface recombination velocity (m.s^-1)
         struct('T',300, ...
                'fmat',@Properties_InGaAs, ...
                'x',0.09, ...
                'Eu',0, ...
                'tj',370e-9, ...
                'Nzr',201, ...
                'Nze',5001, ...
                'Ndop',5e23, ...
                'DopSign',1, ...
                'Sr',[]);
         struct('T',300, ...
                'fmat',@Properties_InGaP, ...
                'x',0.41, ...
                'Eu',0, ...
                'tj',20e-9, ...
                'Nzr',51, ...
                'Nze',501, ...
                'Ndop',1e25, ...
                'DopSign',1, ...
                'Sr',1e2)];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% End %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%